/**
* File: Property.java
* Author: Zachary N. Brown
* Date: October 13, 2022
* Purpose: This class contains the constructor for each
* new property generated by the inputs from the GUI and 
* the methods to change the property state and to display 
* all property details
*/

public class Property implements StateChangeable<Status> {
	
	private String propertyAddress;
	private int bedrooms;
	private int squareFootage;
	private int price;
	private Status status;

	public Property (String propertyAddress, int bedrooms, int squareFootage, int price, Status status) {
		this.propertyAddress = propertyAddress;
		this.bedrooms = bedrooms;
		this.squareFootage = squareFootage;
		this.price=price;
		this.status = Status.FOR_SALE;		
	}
	
	// Implement the abstract method from the StateChangeable class
	public void changeState(Status status) {
		this.status = status;
	}
	 
	@Override
	public String toString() { 
	    return String.format("Address: " + propertyAddress + "\n" +
	    				"Bedrooms: " + bedrooms + "\n" +
	    				"Square Footage: " + squareFootage + "\n" +
	        			"Price: " + price + "\n" +
	    				"Current Status: " + status); 
	}	
}