# -*- coding: utf-8 -*-
"""data_exploration

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X6OmJLe-YRIjOuaKyDc4SPTYcYhLnmKe
"""

"""
    File name: data_exploration.py
    Author: Zachary Brown
    Python Version 3.10.12
    Description: Perform importing, analyzing and cleaning of
    data from a csv file. Read and manipulate temperature data
    from two cities.
"""

import pandas as pd

"""Part I"""

# Read the data into a variable called data. We can assign the
# read functon to the variable for easy reference. We also set
# the unavailable fields to a specific value for easy identification.
data = pd.read_csv('6153237444115dat.csv', na_values=['*', '**', '***', '****',
                                                      '*****', '******'])

# Count the number of rows in the data. It is good practice
# to count the rows and ensure how much data you are initially
# working with.
num_rows = len(data)
print("Number of rows in the data:", num_rows)

# Convert the data to a list and display the column names. 
# Concerting to a list makes it easy to review the data.
column_names = ', '.join(data.columns.tolist())
print("Column names:", column_names)

# Display data types of the columns. This is so we know the
# types of data we are working with.
datatypes = data.dtypes
print("Datatypes of the columns:")
print(datatypes)

# Calculate the mean temperature in Fahrenheit. The mean
# is useful to know for data analysis.
mean_temp_fahrenheit = data['TEMP'].mean()
print("Mean Fahrenheit temperature:", mean_temp_fahrenheit)

# Calculate the standard deviation. Like the mean,
# this information is useful for data analysis.
std_dev_max_temp = data['MAX'].std()
print("Standard deviation of Maximum temperature:", std_dev_max_temp)

# Count the number of unique stations in the data. We will
# need this data for out analysis later.
num_unique_stations = data['USAF'].nunique()
print("Number of unique stations:", num_unique_stations)

"""Part II"""

# Select columns and assign them to a new variable. Doing so makes
# it easier to refer to the data.
selected = data[['USAF', 'YR--MODAHRMN', 'TEMP', 'MAX', 'MIN']]

# Remove all rows from selected that have NoData. This is so
# we can clean the data and make is easier to read.
selected = selected.dropna(subset=['TEMP'])

# Convert Fahrenheit temperatures into Celsius. This is done
# following assignment requirements.
selected['TEMP_Celsius'] = (selected['TEMP'] - 32) / 1.8
selected['MAX_Celsius'] = (selected['MAX'] - 32) / 1.8
selected['MIN_Celsius'] = (selected['MIN'] - 32) / 1.8

# Round the values in Celsius to have 1 decimal place. Rounding
# to 1 decimal place makes the data cleaner and easier to read.
selected = selected.round({'TEMP_Celsius': 1, 'MAX_Celsius': 1, 'MIN_Celsius': 1})

# Save the updated data to a new CSV file. We will want
# to print and check the new data that we have altered.
selected.to_csv('updated_data.csv', index=False)

# Display the updated data. This is to check
# that all of the program logic ran correctly.
print("Updated data with Fahrenheit temperatures converted to Celsius and rounded to 1 decimal place:")
print(selected)

"""Part III"""

# Divide the selection into separate datasets for different stations.
# We will refer to the two stations using their USAF numbers.
kumpula = selected[selected['USAF'] == 29980]
rovaniemi = selected[selected['USAF'] == 28450]

# Save kumpula DataFrame into Kumpula_temps_May_Aug_2017.csv file (CSV format).
# Separating each location into its own csv organizes the data and makes easy reference.
kumpula.to_csv('Kumpula_temps_May_Aug_2017.csv', index=False, float_format='%.1f', sep=',')

# Save rovaniemi DataFrame into Rovaniemi_temps_May_Aug_2017.csv file (CSV format).
rovaniemi.to_csv('Rovaniemi_temps_May_Aug_2017.csv', index=False, float_format='%.1f', sep=',')

# Display a message confirming the completion of the task.
# This is to check that the program logic ran correctly.
print("DataFrames saved successfully.")


"""Part IV (a)"""

# Load the data from the saved CSV files. We must assign each new csv file
# to a variable that reads the data to perform our analytical tasks.
kumpula = pd.read_csv('Kumpula_temps_May_Aug_2017.csv')
rovaniemi = pd.read_csv('Rovaniemi_temps_May_Aug_2017.csv')

# Calculate the median temperature in Celsius for each location.
# Calculating the median temperature is useful for data analysis.
median_temp_kumpula = kumpula['TEMP'].median()
median_temp_rovaniemi = rovaniemi['TEMP'].median()

# Print the results
print("Median temperature in Celsius for Helsinki (Kumpula):", round(median_temp_kumpula, 1))
print("Median temperature in Celsius for Rovaniemi:", round(median_temp_rovaniemi, 1))

"""Part IV (b)"""

# Convert to datetime format. Since we will want to
# select specific dates in the subsequent logic, we
# need to arrange the data into this format.
kumpula['YR--MODAHRMN'] = pd.to_datetime(kumpula['YR--MODAHRMN'], format='%Y%m%d%H%M')
rovaniemi['YR--MODAHRMN'] = pd.to_datetime(rovaniemi['YR--MODAHRMN'], format='%Y%m%d%H%M')

# Select data for May and June. These months can now be selected
# by using the month's number.
kumpula_may = kumpula[kumpula['YR--MODAHRMN'].dt.month == 5]
rovaniemi_may = rovaniemi[rovaniemi['YR--MODAHRMN'].dt.month == 5]

kumpula_june = kumpula[kumpula['YR--MODAHRMN'].dt.month == 6]
rovaniemi_june = rovaniemi[rovaniemi['YR--MODAHRMN'].dt.month == 6]

# Calculate mean, min, and max temperatures for Kumpula and Rovaniemi in May and June.
# This information will help compare the data of the locations. When we pull the data,
# we will also round to 1 decimal place for easy readability.
print("Kumpula Mean, Min, Max temperatures for May:")
print("Mean temperature:", round(kumpula_may['TEMP'].mean(), 1))
print("Minimum temperature:", round(kumpula_may['TEMP'].min(), 1))
print("Maximum temperature:", round(kumpula_may['TEMP'].max(), 1))

print("\nKumpula Mean, Min, Max temperatures for June:")
print("Mean temperature:", round(kumpula_june['TEMP'].mean(), 1))
print("Minimum temperature:", round(kumpula_june['TEMP'].min(), 1))
print("Maximum temperature:", round(kumpula_june['TEMP'].max(), 1))

print("\nRovaniemi Mean, Min, Max temperatures for May:")
print("Mean temperature:", round(rovaniemi_may['TEMP'].mean(), 1))
print("Minimum temperature:", round(rovaniemi_may['TEMP'].min(), 1))
print("Maximum temperature:", round(rovaniemi_may['TEMP'].max(), 1))

print("\nRovaniemi Mean, Min, Max temperatures for June:")
print("Mean temperature:", round(rovaniemi_june['TEMP'].mean(), 1))
print("Minimum temperature:", round(rovaniemi_june['TEMP'].min(), 1))
print("Maximum temperature:", round(rovaniemi_june['TEMP'].max(), 1))

from google.colab import drive
drive.mount('/content/drive')
